language: node_js
env:
  - GH_TOKEN=bf0615c7cb0596a486cd75f1d5f3305a45f881f7
node_js:
  - "node"
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run build && npm run gh-pages
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm run build && npm run gh-pages -- -p "$TRAVIS_BRANCH"
    on:
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
