type: object
properties:
  code:
    type: string
  productId:
    $ref: '#/components/schemas/Identifier'
  classification:
    type: string
    enum:
      - Single
      - Bundle
  productFamilyId:
    $ref: '#/components/schemas/Identifier'
  name:
    type: string
  description:
    type: string
  productAttributeValues:
    uniqueItems: false
    type: array
    items:
      $ref: '#/components/schemas/ProductAttributeValue'
  productBundle:
    uniqueItems: false
    type: array
    items:
      $ref: '#/components/schemas/Product'
  productComponents:
    uniqueItems: false
    type: array
    items:
      $ref: '#/components/schemas/ProductComponent'
  productAttributes:
    uniqueItems: false
    type: array
    items:
      $ref: '#/components/schemas/ProductAttribute'
  attributes:
    uniqueItems: false
    type: array
    items:
      $ref: '#/components/schemas/Attribute'
