type: object
properties:
  productFamilyId:
    $ref: '#/components/schemas/Identifier'
  parentProductFamilyId:
    $ref: '#/components/schemas/Identifier'
  lineOfBusinessId:
    $ref: '#/components/schemas/Identifier'
  name:
    type: string
  description:
    type: string
  productAttributes:
    uniqueItems: false
    type: array
    items:
      $ref: '#/components/schemas/ProductAttribute'
  children:
    uniqueItems: false
    type: array
    items:
      $ref: '#/components/schemas/ProductFamily'
  products:
    uniqueItems: false
    type: array
    items:
      $ref: '#/components/schemas/Product'
  uoM:
    type: string
    enum:
      - Day
      - Hr
      - Min
      - Lesson
      - Item
