type: object
properties:
  id:
    type: string
  productAttributeTypeId:
    $ref: '#/components/schemas/Identifier'
  productAttributeId:
    $ref: '#/components/schemas/Identifier'
  name:
    type: string
  description:
    type: string
  productAttributeValues:
    uniqueItems: false
    type: array
    items:
      $ref: '#/components/schemas/ProductAttributeValue'
