type: object
properties:
  code:
    type: string
  productId:
    $ref: '#/definitions/Identifier'
  classification:
    enum:
      - Single
      - Bundle
    type: string
  productFamilyId:
    $ref: '#/definitions/Identifier'
  name:
    type: string
  description:
    type: string
  productAttributeValues:
    uniqueItems: false
    type: array
    items:
      $ref: '#/definitions/ProductAttributeValue'
  productBundle:
    uniqueItems: false
    type: array
    items:
      $ref: '#/definitions/Product'
  productComponents:
    uniqueItems: false
    type: array
    items:
      $ref: '#/definitions/ProductComponent'
  productAttributes:
    uniqueItems: false
    type: array
    items:
      $ref: '#/definitions/ProductAttribute'
  attributes:
    uniqueItems: false
    type: array
    items:
      $ref: '#/definitions/Attribute'
