type: object
properties:
  id:
    type: string
  productAttributeTypeId:
    $ref: '#/definitions/Identifier'
  productAttributeValueId:
    $ref: '#/definitions/Identifier'
  productAttributeTypeValueId:
    $ref: '#/definitions/Identifier'
  name:
    type: string
  description:
    type: string
  value:
    type: string
  minValue:
    type: string
  maxValue:
    type: string
  valueType:
    type: string
