type: object
properties:
  productFamilyId:
    $ref: '#/definitions/Identifier'
  parentProductFamilyId:
    $ref: '#/definitions/Identifier'
  lineOfBusinessId:
    $ref: '#/definitions/Identifier'
  name:
    type: string
  description:
    type: string
  productAttributes:
    uniqueItems: false
    type: array
    items:
      $ref: '#/definitions/ProductAttribute'
  children:
    uniqueItems: false
    type: array
    items:
      $ref: '#/definitions/ProductFamily'
  products:
    uniqueItems: false
    type: array
    items:
      $ref: '#/definitions/Product'
  uoM:
    enum:
      - Day
      - Hr
      - Min
      - Lesson
      - Item
    type: string
