swagger: '2.0'
info:
  version: '4.0'
  title: Unity API v3.0
  description: >-
    The Unity eCommerce API.<br/><br/>Use the <strong>'Authorize'</strong>
    button to gain access to any API methods that require
    authorization.<br/><br/>
