openapi: 3.0.0
info:
  title: Intouch Unity API 3.0
  description: >-
    The Unity eCommerce API.<br/><br/>Use the <strong>'Authorize'</strong>
    button to gain access to any API methods that require
    authorization.<br/><br/>
  version: 3.0-oas3
servers:
  - url: /
